name: Unit Tests

on:
    push:
        branches:
            - master
            - feature/*
            - bugfix/*
    pull_request:
        branches:
            - master
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ macos-latest, ubuntu-latest ]
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 15
                uses: actions/setup-java@v2
                with:
                    distribution: 'zulu'
                    java-version: 15
            -   name: Build with Maven
                run: mvn verify -DskipITs -DskipSign -B
